service:
  name: ${spring.application.name}
  versions: ${spring.application.version}
spring:
  application:
    name: liquibase-project
    version: 1.0
  liquibase:
    enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myDB
    username: root
    password: Qw123456
    #url: jdbc:h2:file:./db
    #username: u
    #password: 1
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  #h2:
    #console:
      #enabled: true
